### ISSUE TITLE
Chrome version

### ISSUE THREAD

**Issue by karpovas1505** [SAP-samples/sap-community-code-challenge-ui5#35]
Hi colleagues
I have an error when starting npm run test
_[0-0] 2022-06-23T09:53:16.280Z ERROR webdriver: Request failed with status 500 due to session not created: session not created: This version of ChromeDriver only supports Chrome version 101_

If I can't update browser version, how can I resolve issue?

**Comment by mattieharding** [comment]
> Hi colleagues I have an error when starting npm run test _[0-0] 2022-06-23T09:53:16.280Z ERROR webdriver: Request failed with status 500 due to session not created: session not created: This version of ChromeDriver only supports Chrome version 101_
> 
> If I can't update browser version, how can I resolve issue?
Experiencing same issue (finally got a chance to do this challenge) - Hopefully a browser version isn't the reason all your unit test code fails in the future (hoping SAP are ahead of the public Chrome releases but not sure how )? Note - VSCode wants to migrate the application when you first start it too (I choose not to in case that was not expected but then did migrate it when the above did not work - Also asked to install Docker which I didn't think would be required here).

**Comment by karpovas1505** [comment]
> > Hi colleagues I have an error when starting npm run test _[0-0] 2022-06-23T09:53:16.280Z ERROR webdriver: Request failed with status 500 due to session not created: session not created: This version of ChromeDriver only supports Chrome version 101_
> > If I can't update browser version, how can I resolve issue?
> > Experiencing same issue (finally got a chance to do this challenge)
> > Trying to see if installing 101 version of ChromeDriver fixes this but shouldn't this be taken care of by the chromedriver reference in package.json?
> 
> Note - VSCode wants to migrate the application when you first start it too (I choose not to in case that was not expected but then did migrate it when the above did not work - Also asked to install Docker which I didn't think would be required here).

Thanks, @mattieharding.
But I didn't understand the answer. Maybe problem in my English skills

**Comment by mattieharding** [comment]
Sorry - I meant I had the same issue.
But I did get this response from Volker Buzek on Twitter but haven't tried either of these NPM updates yet myself:

"it's a dead loop of technical debt: every time a new chrome version is released, a new chromedriver needs to accompany it for proper remote control
that‘s why a 
$> npm update wdio-ui5-service 
and/or 
$> npm update chromedriver
is a good thing 👍
"

**Comment by nicogeburek** [comment]
Hi all, you want to make sure that your chromedriver version in the `package.json` matches your actual chrome version on your machine. If your chrome gets updated automatically, you might have to [adapt the chromedriver version](https://github.com/SAP-samples/sap-community-code-challenge-ui5/pull/26/commits/5a96b436c873137e46930198905a32f9259aa2f5), at least for now.

**Comment by karpovas1505** [comment]
Thanks @nicogeburek  and @mattieharding 
I've changed chromedriver version to from 101.0.0 to 98.0.0 and it works fine
