### ISSUE TITLE
Unable to start Chromedriver on SAP Business Application Studio 

### ISSUE THREAD

**Issue by Mic4mi** [SAP-samples/sap-community-code-challenge-ui5#50]
Hi colleagues! I'm trying to run the tests on bussiness application studio but, since the only option to run an application is to use the emulated preview of BAS, i'm experience some issues with the chromedriver. Any idea how to solve it? 

Regards!

![error1](https://user-images.githubusercontent.com/61918959/179227621-725d291f-c192-47d2-a361-2e39c9818a8f.png)
![error2](https://user-images.githubusercontent.com/61918959/179227628-5030e9bb-53a7-43da-82ae-36c0bc4aa2b6.png)

**Comment by nicoschoenteich** [comment]
Hi @Mic4mi, sorry for the veery late reply, totally missed this issue. Please also see [this issue](https://github.com/ui5-community/wdi5/issues/329) regarding running wdi5 tests in BAS.
